"""Curated special-livery registry — airline retro / heritage / special paint.

Keyed by REGISTRATION; applying tags them base_interest=1 so they always push.
Matched by registration in scheduled arrivals and (via the aircraft DB) live.

Compiled from published enthusiast/news livery lists (airportspotting.com,
simpleflying.com, flightradar24 blog, airlinegeeks, aeroxplorer, worldairlinenews,
airline pages) covering American, Delta, United, Alaska, JetBlue, Hawaiian,
Spirit, Sun Country, Allegiant, Southwest, and major European / Asia-Pacific /
Middle East carriers. All REAL registrations, no invented tails. Liveries change
(repaints/retirements), so treat as a living list — grow it with the in-app tag
button / POST /api/aircraft/tag.
"""
CURATED_LIVERIES = [
    ('4X-EDF', "special", ['retro', 'el-al']),
    ('9H-AEI', "special", ['retro', 'air-malta']),
    ('9M-MXA', "special", ['special-livery', 'malaysia-40th']),
    ('A6-EQD', "special", ['special-livery', 'emirates-real-madrid']),
    ('A7-BEH', "special", ['special-livery', 'qatar-fifa-2026']),
    ('A9C-FG', "special", ['retro', 'gulf-air']),
    ('AP-BLA', "special", ['retro', 'pia']),
    ('AP-BLT', "special", ['retro', 'pia']),
    ('AP-BMG', "special", ['retro', 'pia']),
    ('B-16217', "special", ['special-livery', 'eva-hello-kitty-pinky']),
    ('B-16331', "special", ['special-livery', 'eva-badtz-maru']),
    ('B-16332', "special", ['special-livery', 'eva-sanrio-joyful-dream']),
    ('B-16333', "special", ['special-livery', 'eva-hello-kitty']),
    ('B-16722', "special", ['special-livery', 'eva-besties-jet']),
    ('B-18055', "special", ['special-livery', 'china-airlines-zootopia2']),
    ('B-18101', "special", ['special-livery', 'china-airlines-pikachu']),
    ('B-58553', "special", ['special-livery', 'starlux-silver-airsorayama']),
    ('B-58554', "special", ['special-livery', 'starlux-gold-airsorayama']),
    ('B-HNK', "special", ['special-livery', 'cathay-spirit-of-hk']),
    ('C-FZUH', "special", ['retro', 'transcanada']),
    ('CS-TJR', "special", ['retro', 'tap']),
    ('D-ABPU', "special", ['special-livery', 'lufthansa-100-berlin']),
    ('D-ABUM', "special", ['retro', 'condor']),
    ('D-ABYN', "special", ['special-livery', 'lufthansa-100-years']),
    ('D-ABYT', "special", ['retro', 'lufthansa']),
    ('D-AICH', "special", ['retro', 'condor']),
    ('D-AIDV', "special", ['retro', 'lufthansa']),
    ('D-AIEM', "special", ['special-livery', 'lufthansa-100-employee']),
    ('D-AIMH', "special", ['special-livery', 'lufthansa-100-years']),
    ('D-AIND', "special", ['special-livery', 'lufthansa-100-years']),
    ('D-AING', "special", ['special-livery', 'lufthansa-100-kerpen']),
    ('D-AINY', "special", ['special-livery', 'lovehansa-pride']),
    ('D-AIXL', "special", ['special-livery', 'lufthansa-100-years']),
    ('EC-KKS', "special", ['special-livery', 'iberia-retro']),
    ('EI-DSY', "special", ['special-livery', 'ita-milano-cortina-2026']),
    ('EI-DVM', "special", ['retro', 'aer-lingus']),
    ('F-GFKJ', "special", ['special-livery', 'air-france-retro']),
    ('G-BNLY', "special", ['retro', 'landor']),
    ('G-BYGC', "special", ['retro', 'boac']),
    ('G-CIVB', "special", ['retro', 'negus']),
    ('G-EUPJ', "special", ['retro', 'bea-red-square']),
    ('G-VPRD', "special", ['special-livery', 'virgin-pride']),
    ('HB-JNA', "special", ['special-livery', 'swiss-peoples-plane']),
    ('HL8227', "special", ['special-livery', 'korean-pyeongchang']),
    ('HS-TGP', "special", ['special-livery', 'thai-retro']),
    ('HS-TKF', "special", ['special-livery', 'thai-royal-barge']),
    ('JA56AN', "special", ['special-livery', 'ana-pokemon-blue']),
    ('JA604A', "special", ['special-livery', 'ana-star-wars']),
    ('JA656J', "special", ['special-livery', 'jal-doraemon']),
    ('JA743A', "special", ['special-livery', 'ana-star-wars-c3po']),
    ('JA784A', "special", ['special-livery', 'ana-pokemon-eevee']),
    ('JA789A', "special", ['special-livery', 'ana-star-wars-bb8']),
    ('JA819A', "special", ['special-livery', 'ana-pokemon-red']),
    ('JA823J', "special", ['special-livery', 'jal-expo-2025']),
    ('JA871A', "special", ['special-livery', 'ana-green-jet']),
    ('JA873A', "special", ['special-livery', 'ana-star-wars-r2d2']),
    ('JA894A', "special", ['special-livery', 'ana-pokemon-pikachu']),
    ('JA923A', "special", ['special-livery', 'ana-pokemon-green']),
    ('LN-RKR', "special", ['special-livery', 'sas-80-years']),
    ('LV-GOO', "special", ['retro', 'aerolineas-argentinas']),
    ('N14102', "special", ['special-livery', 'her-art-here-new-york']),
    ('N14106', "special", ['special-livery', 'her-art-here-california']),
    ('N162AA', "special", ['special-livery', 'stand-up-to-cancer']),
    ('N167AN', "special", ['special-livery', 'flagship-valor']),
    ('N1776R', "special", ['special-livery', 'independence-one']),
    ('N198NV', "special", ['special-livery', 'edc-insomniac']),
    ('N201LV', "special", ['special-livery', 'fred-jones']),
    ('N214WN', "special", ['state-livery', 'maryland-one']),
    ('N220NV', "special", ['special-livery', 'rons-gone-wrong']),
    ('N248AK', "special", ['special-livery', 'boeing-100-years']),
    ('N248WN', "special", ['special-livery', '2000th-737ng']),
    ('N265AK', "special", ['special-livery', 'honoring-those-who-serve']),
    ('N280WN', "special", ['state-livery', 'missouri-one']),
    ('N281WN', "special", ['special-livery', '500th-737']),
    ('N284AV', "special", ['retro', 'avianca']),
    ('N288AK', "special", ['special-livery', 'russell-wilson-dream-big']),
    ('N300SW', "special", ['special-livery', 'spirit-of-kittyhawk']),
    ('N304JB', "special", ['special-livery', 'blueprint']),
    ('N318AS', "special", ['special-livery', 'spirit-of-disneyland']),
    ('N328NV', "special", ['special-livery', 'las-vegas-raiders']),
    ('N341MB', "special", ['special-livery', 'usa250-envoy']),
    ('N37262', "special", ['special-livery', 'united-star-wars']),
    ('N3755D', "special", ['special-livery', 'skyteam']),
    ('N3758Y', "special", ['special-livery', 'skyteam']),
    ('N375HA', "special", ['special-livery', 'oneworld-aloha']),
    ('N3761R', "special", ['special-livery', 'skyteam']),
    ('N381DN', "special", ['special-livery', 'skyteam']),
    ('N391DN', "special", ['special-livery', 'thank-you-employees']),
    ('N392HA', "special", ['special-livery', 'lilo-and-stitch']),
    ('N400QX', "special", ['special-livery', 'idaho-vandals']),
    ('N401QX', "special", ['special-livery', 'washington-state']),
    ('N402QX', "special", ['special-livery', 'montana-grizzlies']),
    ('N403QX', "special", ['special-livery', 'montana-state']),
    ('N407QX', "special", ['special-livery', 'oregon-ducks']),
    ('N411DX', "special", ['special-livery', 'team-usa']),
    ('N421QX', "special", ['retro', 'horizon']),
    ('N435QX', "special", ['special-livery', 'washington-huskies']),
    ('N437QX', "special", ['special-livery', 'boise-state']),
    ('N439WN', "special", ['special-livery', 'donald-ogden']),
    ('N440QX', "special", ['special-livery', 'oregon-state']),
    ('N441QX', "special", ['special-livery', 'uaf-nanooks']),
    ('N443QX', "special", ['special-livery', 'uaa-seawolves']),
    ('N443WN', "special", ['special-livery', 'spirit-of-hope']),
    ('N475UA', "special", ['special-livery', 'united-friend-ship']),
    ('N493AS', "special", ['special-livery', 'more-to-love']),
    ('N500WR', "special", ['special-livery', 'freedom-one']),
    ('N512AS', "special", ['special-livery', 'spirit-of-seattle-boeing']),
    ('N521DN', "special", ['special-livery', 'team-usa']),
    ('N522DZ', "special", ['special-livery', 'la28-olympics']),
    ('N527DN', "special", ['special-livery', 'delta-100-years']),
    ('N531JL', "special", ['special-livery', 'blues-finest-nypd']),
    ('N537AS', "special", ['special-livery', 'friendship-disneyland']),
    ('N537JT', "special", ['special-livery', 'wicked-blue']),
    ('N538AS', "special", ['special-livery', 'star-wars-galaxys-edge']),
    ('N559AS', "special", ['special-livery', 'xaat-kwaani-salmon']),
    ('N560AS', "special", ['special-livery', 'spirit-of-the-islands']),
    ('N569JB', "special", ['special-livery', '10th-anniversary']),
    ('N570AS', "special", ['special-livery', 'honoring-those-who-serve']),
    ('N578UW', "special", ['heritage', 'us-airways']),
    ('N579UW', "special", ['special-livery', 'allegheny-heritage']),
    ('N580UW', "special", ['special-livery', 'america-west-heritage']),
    ('N581UW', "special", ['special-livery', 'piedmont-heritage']),
    ('N582UW', "special", ['special-livery', 'psa-heritage']),
    ('N586JB', "special", ['special-livery', 'i-love-blue-york']),
    ('N587AS', "special", ['special-livery', 'sub-pop-records']),
    ('N589AS', "special", ['special-livery', 'toy-story-4']),
    ('N589DT', "special", ['special-livery', 'delta-100-years']),
    ('N595JB', "special", ['special-livery', 'boston-celtics']),
    ('N598JB', "special", ['special-livery', 'bluemanity']),
    ('N605JB', "special", ['special-livery', 'boston-red-sox']),
    ('N607AS', "special", ['special-livery', 'portland-timbers']),
    ('N615JB', "special", ['special-livery', 'blue-bravest-fdny']),
    ('N628NK', "special", ['special-livery', 'holiday-sweater']),
    ('N632JB', "special", ['special-livery', 'bear-force-one-bruins']),
    ('N633JB', "special", ['special-livery', 'bk-blue-nets']),
    ('N651QX', "special", ['special-livery', 'honoring-those-who-serve']),
    ('N659QX', "special", ['special-livery', 'toy-story-5']),
    ('N66848', "special", ['special-livery', 'march-of-dimes']),
    ('N709JB', "special", ['special-livery', 'binary-code']),
    ('N735AT', "special", ['special-livery', 'flagship-dfw-centennial']),
    ('N742PS', "special", ['heritage', 'psa']),
    ('N744P', "special", ['heritage', 'piedmont']),
    ('N745VJ', "special", ['heritage', 'allegheny']),
    ('N746JB', "special", ['special-livery', 'new-york-jets']),
    ('N751AN', "special", ['special-livery', 'blackman-tribute']),
    ('N75432', "special", ['special-livery', 'ecoskies']),
    ('N75435', "special", ['heritage', 'continental']),
    ('N760MQ', "special", ['heritage', 'tricolor']),
    ('N763JB', "special", ['special-livery', 'jetblue-retro']),
    ('N768AX', "special", ['retro', 'airborne-express']),
    ('N775JB', "special", ['special-livery', 'vets-in-blue']),
    ('N779JB', "special", ['special-livery', 'bluericua']),
    ('N78285', "special", ['special-livery', 'stars-and-stripes-usa250']),
    ('N791AN', "special", ['special-livery', 'oneworld']),
    ('N796AN', "special", ['special-livery', 'oneworld']),
    ('N809SY', "special", ['special-livery', 'minnesota-gophers']),
    ('N826SY', "special", ['special-livery', 'sun-country-1994-retro']),
    ('N8301J', "special", ['special-livery', 'warrior-one']),
    ('N837AW', "special", ['heritage', 'america-west']),
    ('N837NN', "special", ['special-livery', 'oneworld']),
    ('N838AW', "special", ['heritage', 'america-west']),
    ('N840NN', "special", ['special-livery', 'aa-centennial-100']),
    ('N841MH', "special", ['special-livery', 'american-cancer-society']),
    ('N844MH', "special", ['special-livery', 'skyteam']),
    ('N844NN', "special", ['special-livery', 'world-cup']),
    ('N845MH', "special", ['special-livery', 'breast-cancer-rf']),
    ('N8619F', "special", ['state-livery', 'illinois-one']),
    ('N8620H', "special", ['state-livery', 'tennessee-one']),
    ('N8642E', "special", ['special-livery', 'heart-one']),
    ('N8645A', "special", ['special-livery', 'heart-two']),
    ('N8646B', "special", ['state-livery', 'nevada-one']),
    ('N8653A', "special", ['state-livery', 'california-one']),
    ('N8655D', "special", ['state-livery', 'new-mexico-one']),
    ('N8660A', "special", ['state-livery', 'lone-star-one-texas']),
    ('N8681M', "special", ['special-livery', 'triple-crown-one']),
    ('N8690A', "special", ['state-livery', 'colorado-one']),
    ('N8710M', "special", ['state-livery', 'imua-one-hawaii']),
    ('N8719Q', "special", ['special-livery', 'liberty-one']),
    ('N871HK', "special", ['special-livery', 'herbert-kelleher']),
    ('N872CB', "special", ['special-livery', 'colleen-barrett-classic']),
    ('N8766T', "special", ['special-livery', 'rollin-king']),
    ('N886GK', "special", ['special-livery', 'gary-c-kelly']),
    ('N8885Q', "special", ['special-livery', '1000th-737']),
    ('N8891Q', "special", ['special-livery', 'destination-225']),
    ('N8977G', "special", ['state-livery', 'louisiana-one']),
    ('N905NN', "special", ['heritage', 'astrojet']),
    ('N906WN', "special", ['special-livery', 'charles-taylor']),
    ('N91007', "special", ['special-livery', 'stars-and-stripes-usa250']),
    ('N915NN', "special", ['heritage', 'twa']),
    ('N916NN', "special", ['heritage', 'reno-air']),
    ('N917NN', "special", ['heritage', 'aircal']),
    ('N919NN', "special", ['special-livery', 'oneworld']),
    ('N921NN', "special", ['special-livery', 'aa-heritage']),
    ('N927VA', "special", ['special-livery', 'more-to-love']),
    ('N932NK', "special", ['special-livery', 'spirit-untamed']),
    ('N933AK', "special", ['special-livery', 'seattle-kraken']),
    ('N934AA', "special", ['special-livery', '7500th-airbus']),
    ('N938WN', "special", ['special-livery', 'heroes-of-the-heart']),
    ('N945WN', "special", ['state-livery', 'florida-one']),
    ('N953NN', "special", ['special-livery', 'usa250']),
    ('N953WN', "special", ['special-livery', '25th-anniversary']),
    ('N955WN', "special", ['state-livery', 'arizona-one']),
    ('N956WN', "special", ['special-livery', 'jack-vidal']),
    ('N973AN', "special", ['special-livery', 'oneworld']),
    ('N985AK', "special", ['special-livery', 'fifa-world-cup-2026']),
    ('N986NK', "special", ['special-livery', 'super-nintendo-world']),
    ('OD-MRT', "special", ['retro', 'mea']),
    ('OE-LBO', "special", ['retro', 'austrian']),
    ('OH-LWO', "special", ['special-livery', 'finnair-moomin']),
    ('OH-LWP', "special", ['special-livery', 'finnair-moomin']),
    ('OO-SNJ', "special", ['special-livery', 'brussels-tintin']),
    ('OY-KBO', "special", ['retro', 'sas']),
    ('OY-RUT', "special", ['retro', 'danish-air-transport']),
    ('PH-BVA', "special", ['special-livery', 'klm-orange-pride']),
    ('PK-GFM', "special", ['retro', 'garuda-1950s']),
    ('PK-GFN', "special", ['retro', 'garuda']),
    ('PK-GHD', "special", ['retro', 'garuda']),
    ('PK-GIK', "special", ['retro', 'garuda']),
    ('SP-LIM', "special", ['retro', 'lot']),
    ('TC-JNC', "special", ['retro', 'turkish']),
    ('TC-LHH', "special", ['special-livery', 'turkish-500th']),
    ('TF-FIR', "special", ['special-livery', 'icelandair-vatnajokull']),
    ('TF-FIU', "special", ['special-livery', 'icelandair-hekla-aurora']),
    ('TS-IOP', "special", ['retro', 'tunisair']),
    ('VH-VXB', "special", ['special-livery', 'qantas-yananyi-dreaming']),
    ('VH-VXQ', "special", ['retro', 'retro-roo-ii']),
    ('VH-X4A', "special", ['special-livery', 'qantas-minyma-kutjara']),
    ('VH-XZJ', "special", ['special-livery', 'qantas-mendoowoorrji']),
    ('VH-XZP', "special", ['special-livery', 'qantas-retro-roo']),
    ('VH-ZND', "special", ['special-livery', 'qantas-emily-kngwarreye']),
    ('VP-BNT', "special", ['retro', 'aeroflot']),
    ('VT-ATV', "special", ['retro', 'vistara']),
    ('YR-BGG', "special", ['retro', 'tarom']),
    ('ZK-NZE', "special", ['special-livery', 'air-nz-all-black']),
]


_BY_REG = {reg.upper(): (category, tags) for reg, category, tags in CURATED_LIVERIES}


def lookup(reg: str):
    """Return (category, tags) for a curated special-livery tail, else None."""
    return _BY_REG.get((reg or "").upper())


def apply(conn) -> int:
    """Tag every curated livery whose registration exists in the aircraft table."""
    n = 0
    for reg, category, tags in CURATED_LIVERIES:
        cur = conn.execute(
            """UPDATE aircraft SET category=?, interest_tags=?, base_interest=1
               WHERE UPPER(registration)=?""",
            (category, ",".join(tags), reg.upper()))
        n += cur.rowcount
    return n
